#!/bin/bash
set -euxo pipefail
#
#echo $(gcloud redis instances describe redisdb --region ${GOOGLE_CLOUD_REGION} --format "value(host)")
#echo $(gcloud redis instances describe redisdb --region ${GOOGLE_CLOUD_REGION} --format "value(port)")
export REDIS_URL="77.88.00.11"

gcloud functions deploy redis-cachning-java-master \
--entry-point functions.EnvVars \
--runtime java11 \
--memory 512MB \
--set-env-vars REDIS_URL="77.88.00.11" \
--trigger-http